//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieLibraryAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Platforms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_Platforms()
        {
            this.Rel_User_Movie_Platform = new HashSet<Rel_User_Movie_Platform>();
        }
    
        public int Id { get; set; }
        public string Platform { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rel_User_Movie_Platform> Rel_User_Movie_Platform { get; set; }
    }
}
