//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieLibraryAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyMovieLibraryEntities : DbContext
    {
        public MyMovieLibraryEntities()
            : base("name=MyMovieLibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cat_Continents> Cat_Continents { get; set; }
        public virtual DbSet<Cat_Countries> Cat_Countries { get; set; }
        public virtual DbSet<Cat_Platforms> Cat_Platforms { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<Rel_User_Movie> Rel_User_Movie { get; set; }
        public virtual DbSet<Rel_User_Movie_Platform> Rel_User_Movie_Platform { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
