//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieLibraryAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rel_User_Movie_Platform
    {
        public int Id { get; set; }
        public int Id_Rel_User_Movie { get; set; }
        public int IdPlatform { get; set; }
    }
}
